name: Auto-Merge Crowdin PR

on:
  pull_request:
    branches: [main]  # This triggers when a PR targets the main branch
    types: [opened, synchronize, reopened]  # Run on PR creation, sync, or reopening
  workflow_dispatch: # Run manually

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch (l10n_main2)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the source branch of the PR (l10n_main2)
          fetch-depth: 0  # Ensure full commit history is fetched

      - name: Enable auto-merge for Crowdin PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Merge Crowdin PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
