name: Crowdin Action

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    name: Synchronize with Crowdin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "support+bot@crowdin.com"
          git config --global user.name "Crowdin Bot"

      - name: Crowdin Action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: main # Push translations directly to main
          push_translations: true
          push_sources: true
          create_pull_request: false # Prevent PR creation
          commit_message: 'chore: new Crowdin translations by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Check Git Status
        run: git status

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "chore: new Crowdin translations by GitHub Action" || echo "No changes to commit"
          git push
